### ISSUE TITLE
Skip ORTHOFINDER_GO

### ISSUE THREAD

**Issue by chriswyatt1** [Eco-Flow/excon#25]
We should make an option to skip orthofinder go, as maybe a user could just want to run cafe, but is not interested in the go pipeline as well.

--skip_go_assignment            ... perhaps

**Comment by FernandoDuarteF** [comment]
GO assignment is already optional. If no GO files are provided (whether it be from predownloaded GO files or biomoart) GO assignment will not run.

Make it clear in the README.md.
