### ISSUE TITLE
Orthofinder from nf-core

### ISSUE THREAD

**Issue by chriswyatt1** [Eco-Flow/excon#29]

**Comment by FernandoDuarteF** [comment]
Solved in [ae82137](https://github.com/Eco-Flow/excon/commit/ae8213728957d8e922ef572b380121073eae1f7d)

**Comment by chriswyatt1** [comment]
Awesome, that is alot better

**Comment by chriswyatt1** [comment]
Orthofinder needs to have a meta tag, else it fails

**Comment by chriswyatt1** [comment]
Sorted in [298f8e0](https://github.com/Eco-Flow/excon/commit/298f8e014b6726c04f2f627a078a8c0913b254a8)
